name: Apartment Scraper

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create data directory
        run: |
          mkdir -p data
          echo "Created data directory"
      
      - name: Run scraper
        run: |
          echo "Starting apartment scraper..."
          python apartment_scraper.py
          echo "Scraper completed"
      
      - name: Show data files
        run: |
          ls -la data/ || echo "No data directory found"
          cat data/apartment_data.txt || echo "No apartment data file found"
          cat data/change_log.txt || echo "No change log file found"
      
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/
          git commit -m "Update apartment data" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
