name: Apartment Scraper

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for pushing changes
      
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get full history
          ref: main  # Specify the branch
          token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication
      
      - name: Run scraper and show results
        run: |
          echo "Starting apartment scraper..."
          python apartment_scraper.py
          echo "Scraper completed"
          
          echo "\nCurrent working directory:"
          pwd
          
          echo "\nList all files in current directory:"
          ls -la
          
          echo "\nList all files in data directory:"
          ls -la data/ || echo "No data directory found"
          
          echo "\nContents of apartment_data.txt:"
          cat data/apartment_data.txt || echo "No apartment data file found"
          echo "\nContents of change_log.txt:"
          cat data/change_log.txt || echo "No change log file found"
          
          echo "\nGit status:"
          git status
          
          echo "\nGit diff:"
          git diff
      
      - name: Run scraper and show results
        run: |
          echo "Starting apartment scraper..."
          python apartment_scraper.py
          echo "Scraper completed"
          
          echo "\nCurrent working directory:"
          pwd
          
          echo "\nList all files in current directory:"
          ls -la
          
          echo "\nList all files in data directory:"
          ls -la data/ || echo "No data directory found"
          
          echo "\nContents of apartment_data.txt:"
          cat data/apartment_data.txt || echo "No apartment data file found"
          echo "\nContents of change_log.txt:"
          cat data/change_log.txt || echo "No change log file found"
