name: Apartment Scraper

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Run scraper
        run: |
          echo "Starting apartment scraper..."
          python apartment_scraper.py
          echo "Scraper completed"
