name: Apartment Scraper

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get full history
      
      - name: Run scraper and show results
        run: |
          echo "Starting apartment scraper..."
          python apartment_scraper.py
          echo "Scraper completed"
          
          echo "\nData directory contents:"
          ls -la data/ || echo "No data directory found"
          echo "\nContents of apartment_data.txt:"
          cat data/apartment_data.txt || echo "No apartment data file found"
          echo "\nContents of change_log.txt:"
          cat data/change_log.txt || echo "No change log file found"
      
      - name: Save changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git status
          git commit -m "Update apartment data" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
